=== frenchc/jetm/modules/jetm-core/src/java/jetm_config_1_0.dtd
<!--
  Copyright (c) 2004, 2005, 2006 void.fm
  All rights reserved.

  Redistribution and use in source and binary forms, with or without modification,
  are permitted provided that the following conditions are met:

  * Redistributions of source code must retain the above copyright notice, this list
    of conditions and the following disclaimer.

  * Redistributions in binary form must reproduce the above copyright notice, this
    list of conditions and the following disclaimer in the documentation and/or
    other materials provided with the distribution.

  * Neither the name void.fm nor the names of its contributors may be
    used to endorse or promote products derived from this software without specific
    prior written permission.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
  OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
  OF THE POSSIBILITY OF SUCH DAMAGE.

 -->

<!--
 Use this doctype for jetm xml configuration files.

 <!DOCTYPE jetm-config PUBLIC "-// void.fm //DTD JETM Config 1.0//EN"
                              "http://jetm.void.fm/dtd/jetm_config_1_0.dtd">
 -->


<!ELEMENT jetm-config ((monitor-type|monitor-class)?, (timer-type|timer-class)?, aggregator-chain*, extension*)>

<!ELEMENT monitor-type (#PCDATA)>
<!ELEMENT monitor-class (#PCDATA)>
<!ELEMENT timer-type (#PCDATA)>
<!ELEMENT timer-class (#PCDATA)>
<!ELEMENT aggregator-chain (chain-element+,chain-root)>
<!ELEMENT extension (plugin)*>

<!ELEMENT chain-root (aggregator-class, properties?)>
<!ELEMENT chain-element (aggregator-class, properties?)>
<!ELEMENT aggregator-class (#PCDATA)>
<!ELEMENT properties (property)*>
<!ELEMENT plugin (plugin-class,properties?)>

<!ELEMENT plugin-class (#PCDATA)>

<!ELEMENT property (#PCDATA)>

<!ATTLIST jetm-config autostart (true|false) "false">

<!ATTLIST property name CDATA #REQUIRED>

=== frenchc/jetm/modules/jetm-core/src/test/resources/etm/core/configuration/files/valid_1_0/aggregator-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE jetm-config PUBLIC "-// void.fm //DTD JETM Config 1.0//EN" "http://jetm.void.fm/dtd/jetm_config_1_0.dtd">
<jetm-config>
  <monitor-class>etm.core.configuration.mockup.TestMonitor</monitor-class>
  <timer-class>etm.core.configuration.mockup.TestTimer</timer-class>
  <aggregator-chain>
    <chain-element>
      <aggregator-class>etm.core.configuration.mockup.TestAggregator</aggregator-class>
      <properties>
        <property name="booleanTrue">true</property>
        <property name="booleanFalse">false</property>
        <property name="longValue">12124234324234</property>
        <property name="intValue">12</property>
        <property name="stringValue">testString</property>
        <property name="clazzValue">java.util.HashMap</property>
        <property name="listValue">value1</property>
        <property name="listValue">value2</property>
        <property name="mapValue.key1">value1</property>
        <property name="mapValue.key2">value2</property>
        <property name="mapValue.key3">value3</property>
      </properties>
    </chain-element>
    <chain-root>
      <aggregator-class>etm.core.aggregation.RootAggregator</aggregator-class>
    </chain-root>
  </aggregator-chain>
</jetm-config>
